### ISSUE TITLE
Pulumi-python docker image have many vulnerabilities that needs to be fixed

### ISSUE THREAD

**Issue by abhishekmahajan0709222** [pulumi/pulumi-docker-containers#206]
### What happened?

We are using pulumi-python image as base in our dockerfile

Upon running trivy scan, we found some critical and high vulnerabilities with some packages

1. Libexpat1(CVE-2023-52425)
2. zlib1g(CVE-2023-45853)

### Example

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for the heads-up! We're looking into it.

**Comment by julienp** [comment]
Hi, the expat issue was fixed in the base python image we use.

The zlib issue is a false positive. The vulnerability is only present if you install the `minizip` package, which the image does not do. See https://security-tracker.debian.org/tracker/CVE-2023-45853 for full details.

We are also improving our automated scanning for our containers, so we can better track and fix these issues.
