### ISSUE TITLE
Mirror to GHCR

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi-docker-containers#64]
## Issue details

I think it would be nice if we could mirror our Docker Hub images to GHCR. The nice thing about GHCR is that the URL structure is easy to search and replace: ghcr.io/pulumi/pulumi vs docker.io/pulumi/pulumi.

GHCR isn't subject to rate limiting and also provides the "package" UI on the main repo.

**Comment by jkodroff** [comment]
This should be fairly straightforward:

# The Easy (short-term) Way

Copy/past the code in <https://github.com/pulumi/pulumi-docker-containers/blob/main/.github/workflows/sync-ecr.yml>, replace all ECR refs with GHCR refs.

# The Harder (but easier in the long-term) Way

Change `sync-ecr.yml` so to a generic sync that expects the destination repo as part of the `repository_dispatch` event.  However, in order to do this, we might need to alter `pulumictl` so that it can accept additional args.  Need to look into it further.

# The Super-Duper Ideal Way

See if there's an existing action that already does this.  I didn't find one, but I did not do an exhaustive search when I wrote the ECR Sync workflow.

**Comment by jkodroff** [comment]
Per convo with @stack72 we came to an agreement that copy/paste was the appropriate solution here.  Reusable workflows are not as capable as we need for the use case.

**Comment by jkodroff** [comment]
@rawkode The PR for this has been merged, but we still need to set the permissions so that the packages are visible.

**Comment by stack72** [comment]
These images are now available on https://github.com/orgs/pulumi/packages/
